# Generated by Django 5.2.4 on 2025-07-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('tech', 'Tech'), ('conference', 'Conference'), ('art', 'Art'), ('sports', 'Sports')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
