# Generated by Django 5.2.4 on 2025-07-28 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='price_normal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Normal ticket price', max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='price_vip',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='VIP ticket price', max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
