# Generated by Django 5.2.4 on 2025-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_venue_event_location_event_price_normal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
