# Generated by Django 5.2.4 on 2025-07-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_popular',
        ),
    ]
