# Generated by Django 5.2.4 on 2025-07-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10),
            preserve_default=False,
        ),
    ]
