# Generated by Django 5.2.4 on 2025-07-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
